server:
  port: 8080 #使用的端口号

spring:
  datasource:
    master:
      name: master1
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://172.16.0.49:3306/mos6.2_gsms?useSSL=false&autoReconnect=true&sessionVariables=FOREIGN_KEY_CHECKS=0&useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      maxTotal: 200
      maxIdle: 8
      minIdle: 8
      initialSize: 10
      maxWaitMillis: 3000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      maxLifetime: 60000  #毫秒级

    master2:
      name: master2
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://172.16.0.112:3306/mos6.2_gsms?useSSL=false&autoReconnect=true&sessionVariables=FOREIGN_KEY_CHECKS=0&useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      maxTotal: 200
      maxIdle: 8
      minIdle: 8
      initialSize: 10
      maxWaitMillis: 3000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      maxLifetime: 60000  #毫秒级

    slave:
      name: slave1
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://172.16.0.112:3306/mos6.2_gsms?useSSL=false&autoReconnect=true&sessionVariables=FOREIGN_KEY_CHECKS=0&useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      maxTotal: 200
      maxIdle: 8
      minIdle: 8
      initialSize: 10
      maxWaitMillis: 3000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      maxLifetime: 60000  #毫秒级

    slave2:
      name: slave2
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://172.16.0.49:3306/mos6.2_gsms?useSSL=false&autoReconnect=true&sessionVariables=FOREIGN_KEY_CHECKS=0&useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      maxTotal: 200
      maxIdle: 8
      minIdle: 8
      initialSize: 10
      maxWaitMillis: 3000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      maxLifetime: 60000  #毫秒级


mybatis:
  mapper-locations: classpath:com.sinon.hello.mapper/*Mapper.xml
  type-aliases-package: com.sinon.hello.entity

#showSql
logging:
  level:
    com.sinon.hello.mapper : debug

mastercount:
  num: 2
slavecount:
  num: 2
