server:
  port: 8080 #使用的端口号

spring:
  datasource:
    master:
      name: master1
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://172.16.0.49:3306/mos6.2_gsms?useSSL=false&autoReconnect=true&sessionVariables=FOREIGN_KEY_CHECKS=0&useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      maxTotal: 200
      maxIdle: 8
      minIdle: 8
      initialSize: 10
      maxWaitMillis: 3000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      maxLifetime: 60000  #毫秒级

    master2:
      name: master2
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://172.16.0.112:3306/mos6.2_gsms?useSSL=false&autoReconnect=true&sessionVariables=FOREIGN_KEY_CHECKS=0&useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      maxTotal: 200
      maxIdle: 8
      minIdle: 8
      initialSize: 10
      maxWaitMillis: 3000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      maxLifetime: 60000  #毫秒级

    slave:
      name: slave1
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://172.16.0.112:3306/mos6.2_gsms?useSSL=false&autoReconnect=true&sessionVariables=FOREIGN_KEY_CHECKS=0&useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      maxTotal: 200
      maxIdle: 8
      minIdle: 8
      initialSize: 10
      maxWaitMillis: 3000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      maxLifetime: 60000  #毫秒级

    slave2:
      name: slave2
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://172.16.0.49:3306/mos6.2_gsms?useSSL=false&autoReconnect=true&sessionVariables=FOREIGN_KEY_CHECKS=0&useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      maxTotal: 200
      maxIdle: 8
      minIdle: 8
      initialSize: 10
      maxWaitMillis: 3000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      maxLifetime: 60000  #毫秒级

  redis:
    #ip
    host: 192.168.72.128
    #端口
    port: 6379
    #密码，默认为空
    #password：
    # 连接超时时间（毫秒）
    timeout: 0
    # Redis数据库索引（默认为0）
    database: 0
    #连接池
    pool:
      #连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0

mybatis:
  mapper-locations: classpath:com.sinon.hello.mapper/*Mapper.xml
  type-aliases-package: com.sinon.hello.entity

#showSql
logging:
  level:
    com:
      sinon:
        hello:
          mapper: debug

master-datasource-count:
  num: 2
slave-datasource-count:
  num: 2
